#!/bin/bash
set -e

install_fzf () {
  FZF_URL=https://github.com/junegunn/fzf/releases/download/0.29.0/fzf-0.29.0-linux_amd64.tar.gz
  curl -L \
    -o fzf.tar.gz \
    "$FZF_URL"
  tar xzvf fzf.tar.gz
  mv ./fzf /home/gitpod/.local/bin/
}

install_starship () {
  sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --bin-dir /home/gitpod/.local/bin -y
  mkdir -p /home/gitpod/.config
  mkdir -p /home/gitpod/.cache/starship
}


mkdir -p /home/gitpod/.local/bin
cp ./.zshrc /home/gitpod/.zshrc
install_fzf
install_starship
